import ExcelJS from "exceljs";
import type { SuperAdminContactRow } from "@/lib/super-admin/contacts-types";
import type {
  ContactHasFilter,
  ContactPlanFilter,
  ContactStatusFilter,
  ContactTypeFilter,
  SuperAdminContactFilters,
  SuperAdminSchoolOption,
} from "@/lib/super-admin/contacts-types";
import {
  buildContactsCsv,
  contactTypeLabel,
} from "@/lib/super-admin/contacts-utils";
import { schoolLifecycleStatusLabel } from "@/lib/super-admin/school-lifecycle";

export interface ContactsExportMetadata {
  generatedBy: string;
  generatedOn: string;
  exportedBy: string;
  filters: {
    role: string;
    school: string;
    plan: string;
    status: string;
    phoneFilter: string;
    emailFilter: string;
  };
}

const DATA_HEADERS = [
  "Name",
  "Type",
  "Source",
  "School",
  "Phone",
  "Email",
  "Plan",
  "School Status",
  "Health Score",
  "Assigned Class",
  "Linked Students",
] as const;

function filterLabel(
  value: string,
  map: Record<string, string>,
  fallback = "All"
): string {
  return map[value] ?? fallback;
}

export function buildExportMetadata(
  filters: SuperAdminContactFilters,
  schoolOptions: SuperAdminSchoolOption[],
  exportedBy: string
): ContactsExportMetadata {
  const schoolName =
    filters.schoolId != null
      ? (schoolOptions.find((s) => s.id === filters.schoolId)?.name ??
        filters.schoolId)
      : "All schools";

  return {
    generatedBy: "Adakaro",
    generatedOn: new Date().toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    }),
    exportedBy,
    filters: {
      role: filterLabel(filters.type, {
        all: "All",
        admin: "Admins",
        teacher: "Teachers",
        parent: "Parents",
      }),
      school: schoolName,
      plan: filterLabel(filters.plan, {
        all: "All plans",
        free: "Free",
        paid: "Paid",
      }),
      status: filterLabel(filters.schoolStatus, {
        all: "All (excl. archived)",
        setup: "Setup",
        active: "Active",
        inactive: "Inactive",
        archived: "Archived",
      }),
      phoneFilter: filterLabel(filters.hasPhone, {
        all: "Any",
        yes: "Has phone",
        no: "No phone",
      }),
      emailFilter: filterLabel(filters.hasEmail, {
        all: "Any",
        yes: "Has email",
        no: "No email",
      }),
    },
  };
}

function metadataLines(metadata: ContactsExportMetadata): string[] {
  return [
    `Generated by: ${metadata.generatedBy}`,
    `Generated on: ${metadata.generatedOn}`,
    `Exported by: ${metadata.exportedBy}`,
    "Filters Applied:",
    `- Role: ${metadata.filters.role}`,
    `- School: ${metadata.filters.school}`,
    `- Plan: ${metadata.filters.plan}`,
    `- Status: ${metadata.filters.status}`,
    `- Phone Filter: ${metadata.filters.phoneFilter}`,
    `- Email Filter: ${metadata.filters.emailFilter}`,
    "",
  ];
}

export function buildContactsCsvWithMetadata(
  rows: SuperAdminContactRow[],
  metadata: ContactsExportMetadata
): string {
  const meta = metadataLines(metadata).join("\n");
  return `\uFEFF${meta}${buildContactsCsv(rows)}`;
}

function rowToValues(row: SuperAdminContactRow): string[] {
  return [
    row.name,
    contactTypeLabel(row),
    row.sourceLabel,
    row.schoolName,
    row.phone ?? "",
    row.email ?? "",
    row.schoolPlan,
    schoolLifecycleStatusLabel(row.schoolStatus),
    row.healthScore != null ? String(row.healthScore) : "",
    row.assignedClass ?? "",
    row.linkedStudents ?? "",
  ];
}

export async function buildContactsExcelBuffer(
  rows: SuperAdminContactRow[],
  metadata: ContactsExportMetadata
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = metadata.generatedBy;
  workbook.created = new Date();

  const sheet = workbook.addWorksheet("Contacts", {
    views: [{ state: "frozen", ySplit: 10, xSplit: 0 }],
  });

  const metaRows = metadataLines(metadata).map((line) => [line]);
  for (const row of metaRows) {
    sheet.addRow(row);
  }

  const headerRow = sheet.addRow([...DATA_HEADERS]);
  headerRow.font = { bold: true };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FFE2E8F0" },
  };
  headerRow.alignment = { vertical: "middle", wrapText: true };

  for (const row of rows) {
    const dataRow = sheet.addRow(rowToValues(row));
    dataRow.alignment = { vertical: "top", wrapText: true };
  }

  const headerRowNumber = metaRows.length + 1;
  const lastCol = DATA_HEADERS.length;
  const lastDataRow = headerRowNumber + rows.length;
  sheet.autoFilter = {
    from: { row: headerRowNumber, column: 1 },
    to: { row: lastDataRow, column: lastCol },
  };

  sheet.columns.forEach((column, index) => {
    const header = DATA_HEADERS[index] ?? "";
    let max = header.length;
    sheet.eachRow((row, rowNumber) => {
      if (rowNumber <= metaRows.length) return;
      const cell = row.getCell(index + 1);
      const value = cell.value?.toString() ?? "";
      max = Math.max(max, Math.min(value.length, 48));
    });
    column.width = Math.max(max + 2, 12);
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}