/// Production Supabase settings for the Adakaro mobile app.
///
/// Must stay aligned with the Next.js web client (`lib/supabase/client.ts`), which uses
/// `NEXT_PUBLIC_SUPABASE_URL` and `NEXT_PUBLIC_SUPABASE_ANON_KEY`.
///
/// **Auth flow (same as web):** `signInWithPassword` with the Supabase Auth email.
/// Non-email identifiers are resolved server-side via RPC `resolve_sign_in_email` (see migrations
/// `00131` / `00132`) before password sign-in — equivalent to the web server resolver.
///
/// **Precedence at runtime** (see [Env]): `--dart-define` > `.env` > values below.
/// Use `--dart-define` or `.env` for a different Supabase project; do not edit this file for that.
abstract final class SupabaseConfig {
  /// Same as web `NEXT_PUBLIC_SUPABASE_URL` (project ref `csdhkpqrgmejivbpdxjx`).
  static const String supabaseUrl =
      'https://csdhkpqrgmejivbpdxjx.supabase.co';

  /// Same as web `NEXT_PUBLIC_SUPABASE_ANON_KEY` (Dashboard → Settings → API → **anon public**).
  ///
  /// Leave empty in source control. Set `SUPABASE_ANON_KEY` in `mobile/.env` (from your web
  /// `.env.local`) or pass `--dart-define=SUPABASE_ANON_KEY=...` when running/building.
  /// Never use the **service_role** key in the app.
  static const String supabaseAnonKey = '';
}
